/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogCards: typeof import('./src/components/dashboard/BlogCards.vue')['default']
    CardHeaderFooter: typeof import('./src/components/shared/CardHeaderFooter.vue')['default']
    DefaultText: typeof import('./src/components/style-components/typography/DefaultText.vue')['default']
    EarningReports: typeof import('./src/components/dashboard/EarningReports.vue')['default']
    Heading: typeof import('./src/components/style-components/typography/Heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RevenueCard: typeof import('./src/components/dashboard/RevenueCard.vue')['default']
    RevenueProducts: typeof import('./src/components/dashboard/RevenueProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shadow: typeof import('./src/components/style-components/shadow/Shadow.vue')['default']
    TotalFolllowers: typeof import('./src/components/dashboard/TotalFolllowers.vue')['default']
    TotalIncome: typeof import('./src/components/dashboard/TotalIncome.vue')['default']
    UiChildCard: typeof import('./src/components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./src/components/shared/UiParentCard.vue')['default']
    UiParentCardLogo: typeof import('./src/components/shared/UiParentCardLogo.vue')['default']
    UiTableCard: typeof import('./src/components/shared/UiTableCard.vue')['default']
    UiTextfieldPrimary: typeof import('./src/components/shared/UiTextfieldPrimary.vue')['default']
    WidgetCard: typeof import('./src/components/shared/WidgetCard.vue')['default']
    WidgetCardv2: typeof import('./src/components/shared/WidgetCardv2.vue')['default']
  }
}
